title: Squidgeefish
description: Electronic/mechanical/software-related shenanigans of questionable advisability
url: https://squidgeefish.com

remote_theme: squidgeefish/midnight

collections:
    projects:
        output: true
        permalink: /:collection/:name/
